name: deploy

on:
  push:
    branches:[main] # 当代码推送到 main 分支时触发
  paths-ignore: - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版的虚拟机来运行任务
    
    steps:
      # 下载源码
      # 检出你的仓库并下载里面的代码到runner中，actions、checkout@v2是官方自己造的轮子，拿来即用
      - name: Checkout
        uses: actions/checkout@v2  # 检出代码到工作区

      # 打包构建
      - name: Build
        uses: actions/setup-node@master  # 设置 Node.js 环境
        with:
          node-version: '20.x'  # 指定 Node.js 版本

      - name: Install dependencies
        run: npm install  # 安装项目依赖
        run: npm run build  # 打包

      # 部署到gh-pages分支
      - name: Deploy
        uses:peaceiris/actions-gh-pages@v3
        with:
        # 部署分支
        branch: gh-pages
        # deploy_key: ${{ secrets.CICDDEMO }} # 部署秘钥，在项目的Settings/Secrets 中配置
        publish_dir: ./dist # 部署打包后的dist目录
        github_token: ${{ secrets.CICDDEMO }} # secret 名
        user_name: ${{ secrets.MY_USER_NAME }}
        user_email: ${{ secrets.MY_USER_EMAIL }}
        commit_message: 自动部署 # 部署时的 git 提交信息
        run: npm test  # 运行测试